export const TAGITCoreDemoABI = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assets",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "state", type: "uint8", internalType: "enum TAGITCoreDemo.State" },
      { name: "owner", type: "address", internalType: "address" },
      { name: "mintedAt", type: "uint256", internalType: "uint256" },
      { name: "lastUpdated", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "changeState",
    inputs: [
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "newState", type: "uint8", internalType: "enum TAGITCoreDemo.State" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAsset",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct TAGITCoreDemo.Asset",
        components: [
          { name: "name", type: "string", internalType: "string" },
          { name: "state", type: "uint8", internalType: "enum TAGITCoreDemo.State" },
          { name: "owner", type: "address", internalType: "address" },
          { name: "mintedAt", type: "uint256", internalType: "uint256" },
          { name: "lastUpdated", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenIds",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tokenIds",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AssetMinted",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      { name: "owner", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StateChanged",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "oldState", type: "uint8", indexed: false, internalType: "enum TAGITCoreDemo.State" },
      { name: "newState", type: "uint8", indexed: false, internalType: "enum TAGITCoreDemo.State" },
      { name: "changedBy", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyExists", inputs: [] },
  { type: "error", name: "DoesNotExist", inputs: [] },
  { type: "error", name: "NotAdmin", inputs: [] },
] as const;
